import type { Job, Candidate, TeamMember, Invoice } from "./types";

// ─────────────────────────────────────────────
// JOBS
// ─────────────────────────────────────────────

export const JOBS: Job[] = [
  {
    id: "job-001",
    title: "Senior Software Engineer",
    contractType: "permanent",
    jobType: "full_time",
    locationType: "hybrid",
    postcode: "SE1 9SG",
    minSalary: 70000,
    maxSalary: 90000,
    salaryType: "per_year",
    location: "London, UK (Hybrid)",
    advertCopy: `We're looking for a Senior Software Engineer to join our growing product team in London. You'll be working on a modern TypeScript/React stack, building features used by thousands of businesses across the UK.

You'll work closely with the product and design team to ship high-quality, well-tested code. We operate in small, autonomous teams with a strong culture of code review and continuous improvement.

**What you'll do:**
- Design and build new features across our web and API stack
- Lead technical discussions and mentor junior engineers
- Contribute to architectural decisions and engineering best practices
- Collaborate with product managers and designers to define requirements

**What we offer:**
- £70,000–£90,000 depending on experience
- Hybrid working — 2 days in our London Bridge office
- 30 days holiday + bank holidays
- Private healthcare, pension, and equity`,
    essentialCriteria: [
      { id: "ec-1", text: "4+ years of commercial TypeScript/JavaScript experience", type: "essential" },
      { id: "ec-2", text: "Strong React knowledge with experience in production applications", type: "essential" },
      { id: "ec-3", text: "Experience with Node.js or similar backend technology", type: "essential" },
      { id: "ec-4", text: "Comfortable with cloud infrastructure (AWS, GCP, or Azure)", type: "essential" },
      { id: "ec-5", text: "Experience with SQL databases and query optimisation", type: "essential" },
    ],
    desirableCriteria: [
      { id: "dc-1", text: "Experience with Next.js and serverless architectures", type: "desirable" },
      { id: "dc-2", text: "Previous experience in a startup or scale-up environment", type: "desirable" },
      { id: "dc-3", text: "Contributions to open-source projects", type: "desirable" },
    ],
    qualifyingQuestions: [
      { id: "qq-1", question: "Do you have the right to work in the UK without sponsorship?", qualifyingAnswer: "yes" },
      { id: "qq-2", question: "Do you have at least 4 years of commercial software engineering experience?", qualifyingAnswer: "yes" },
    ],
    collectionMethod: "collect_cvs",
    status: "live",
    postedAt: "2026-04-22T09:00:00Z",
    endDate: "2026-05-20T23:59:59Z",
    daysLive: 14,
    dayRate: 19,
    applicationCount: 12,
    runningCost: 266,
  },
  {
    id: "job-002",
    title: "Marketing Manager",
    contractType: "permanent",
    jobType: "full_time",
    locationType: "hybrid",
    postcode: "M2 3AW",
    minSalary: 45000,
    maxSalary: 55000,
    salaryType: "per_year",
    location: "Manchester, UK (Hybrid)",
    advertCopy: `We're hiring a Marketing Manager to own our growth strategy at a critical stage in our company's development. Based in Manchester, you'll be part of a lean, ambitious team that's building something genuinely different in the B2B SaaS space.

This is a hands-on role — you'll be as comfortable writing campaign briefs as you are pulling data from Google Analytics and presenting results to the leadership team.

**What you'll do:**
- Develop and execute multi-channel marketing campaigns
- Own SEO, paid search, and social media strategy
- Manage the content calendar and agency relationships
- Report on marketing performance against pipeline targets

**What we offer:**
- £45,000–£55,000 depending on experience
- Flexible hybrid working from our Manchester city centre office
- 28 days holiday + bank holidays
- Team socials and annual company trip`,
    essentialCriteria: [
      { id: "ec-1", text: "3+ years B2B marketing experience, ideally in SaaS or tech", type: "essential" },
      { id: "ec-2", text: "Proven track record of running successful demand generation campaigns", type: "essential" },
      { id: "ec-3", text: "Strong analytical skills — comfortable with GA4, HubSpot or similar", type: "essential" },
      { id: "ec-4", text: "Excellent copywriting and communication skills", type: "essential" },
    ],
    desirableCriteria: [
      { id: "dc-1", text: "Experience with account-based marketing (ABM)", type: "desirable" },
      { id: "dc-2", text: "Knowledge of marketing automation platforms", type: "desirable" },
      { id: "dc-3", text: "Experience managing agency relationships", type: "desirable" },
    ],
    qualifyingQuestions: [
      { id: "qq-1", question: "Do you have the right to work in the UK without sponsorship?", qualifyingAnswer: "yes" },
      { id: "qq-2", question: "Do you have at least 3 years of B2B marketing experience?", qualifyingAnswer: "yes" },
      { id: "qq-3", question: "Are you based in or willing to relocate to Greater Manchester?", qualifyingAnswer: "yes" },
    ],
    collectionMethod: "collect_cvs",
    status: "live",
    postedAt: "2026-04-28T10:30:00Z",
    endDate: null,
    daysLive: 8,
    dayRate: 19,
    applicationCount: 10,
    runningCost: 152,
  },
  {
    id: "job-003",
    title: "HR Business Partner",
    contractType: "permanent",
    jobType: "full_time",
    locationType: "fixed",
    postcode: "BS1 5TR",
    minSalary: 40000,
    maxSalary: 50000,
    salaryType: "per_year",
    location: "Bristol, UK (On-site 3 days)",
    advertCopy: `We're looking for an experienced HR Business Partner to support our Bristol-based operations team of 150+ people. This is a pivotal role working closely with senior leaders to shape culture, manage ER cases, and drive our people agenda.

You'll be a trusted advisor to managers — coaching them through performance conversations, supporting change programmes, and ensuring compliance with UK employment law.

**What you'll do:**
- Partner with department heads to deliver the people strategy
- Lead ER casework including disciplinaries, grievances, and absence management
- Support talent acquisition alongside our in-house recruitment team
- Drive engagement and wellbeing initiatives

**What we offer:**
- £50,000–£60,000 depending on experience
- 3 days on-site in our Bristol Temple Quay office
- CIPD CPD budget and study support
- 28 days holiday + bank holidays, private dental`,
    essentialCriteria: [
      { id: "ec-1", text: "CIPD Level 5 qualified or above", type: "essential" },
      { id: "ec-2", text: "4+ years HR generalist experience, including ER case management", type: "essential" },
      { id: "ec-3", text: "Strong knowledge of UK employment law", type: "essential" },
      { id: "ec-4", text: "Proven track record as a trusted HR advisor to senior managers", type: "essential" },
    ],
    desirableCriteria: [
      { id: "dc-1", text: "CIPD Level 7 or working towards it", type: "desirable" },
      { id: "dc-2", text: "Experience supporting organisational design or restructuring", type: "desirable" },
      { id: "dc-3", text: "Background in a professional services or operations environment", type: "desirable" },
    ],
    qualifyingQuestions: [
      { id: "qq-1", question: "Do you have the right to work in the UK without sponsorship?", qualifyingAnswer: "yes" },
      { id: "qq-2", question: "Do you hold a CIPD Level 5 qualification or above?", qualifyingAnswer: "yes" },
    ],
    collectionMethod: "collect_cvs",
    status: "closed",
    postedAt: "2026-04-01T09:00:00Z",
    endDate: "2026-04-30T23:59:59Z",
    daysLive: 29,
    dayRate: 19,
    applicationCount: 9,
    runningCost: 551,
  },
];

// ─────────────────────────────────────────────
// CANDIDATES — Job 001: Senior Software Engineer
// ─────────────────────────────────────────────

export const CANDIDATES: Candidate[] = [
  // ── Job 001 ──────────────────────────────────
  {
    id: "c-001-01",
    jobId: "job-001",
    name: "James Thornton",
    email: "james.thornton@email.co.uk",
    phone: "07700 900 112",
    location: "London, UK",
    appliedAt: "2026-04-23T10:14:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 91,
    tier: 6,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 95, rationale: "6 years commercial experience across multiple production products" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 92, rationale: "Led React migration at current employer; built component library from scratch" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 90, rationale: "Node.js used extensively; also has Go experience" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 88, rationale: "AWS certified; used Lambda, ECS and RDS in production" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 85, rationale: "PostgreSQL experience at scale; mentions index optimisation" },
      { criterionId: "dc-1", criterionText: "Next.js and serverless", type: "desirable", score: 90, rationale: "Multiple Next.js projects listed; serverless experience noted" },
      { criterionId: "dc-2", criterionText: "Startup/scale-up", type: "desirable", score: 95, rationale: "Current role is at a Series B startup; prior role also early-stage" },
    ],
    status: "shortlisted",
    cv: {
      summary: "Senior Software Engineer with 6 years of experience building scalable web applications and APIs. Passionate about clean code, developer experience, and shipping products that users love. Currently at a Series B fintech building TypeScript microservices.",
      experience: [
        {
          title: "Senior Software Engineer",
          company: "Monflow Technologies",
          location: "London, UK",
          startDate: "2023-03",
          endDate: null,
          current: true,
          description: "Technical lead on the core payments API, serving 200k+ daily transactions. Migrated legacy Angular codebase to React/Next.js, reducing bundle size by 40%. Introduced Vitest and achieved 80% test coverage across the team.",
        },
        {
          title: "Software Engineer",
          company: "Veritas Digital",
          location: "London, UK",
          startDate: "2020-06",
          endDate: "2023-02",
          current: false,
          description: "Full-stack engineer on a B2B SaaS platform. Built a real-time notification system using WebSockets and Redis. Deployed and maintained Node.js services on AWS ECS. Mentored two junior engineers.",
        },
        {
          title: "Junior Developer",
          company: "Cogent Software",
          location: "Reading, UK",
          startDate: "2019-09",
          endDate: "2020-05",
          current: false,
          description: "Worked on internal tooling and client-facing React dashboards. First commercial role following university placement year.",
        },
      ],
      education: [
        { institution: "University of Bristol", qualification: "BSc", subject: "Computer Science", startYear: 2015, endYear: 2019, grade: "2:1" },
      ],
      skills: ["TypeScript", "React", "Next.js", "Node.js", "Go", "PostgreSQL", "AWS", "Docker", "Kubernetes", "GraphQL", "Redis"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-001-02",
    jobId: "job-001",
    name: "Priya Kapoor",
    email: "priya.kapoor@outlook.com",
    phone: "07700 900 234",
    location: "London, UK",
    appliedAt: "2026-04-23T14:52:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 88,
    tier: 6,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 92, rationale: "5 years experience, primarily TypeScript for the last 3" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 90, rationale: "React expert; gave conference talk on React performance" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 80, rationale: "Node.js experience but primarily frontend-focused" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 82, rationale: "GCP experience with Cloud Run and BigQuery" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 88, rationale: "PostgreSQL and BigQuery mentioned across multiple roles" },
      { criterionId: "dc-1", criterionText: "Next.js and serverless", type: "desirable", score: 85, rationale: "Next.js used at current employer for marketing and app" },
    ],
    status: "shortlisted",
    cv: {
      summary: "Software Engineer with 5 years of experience specialising in frontend architecture and React applications. Track record of delivering performant, accessible UIs. Speaker at React London 2025.",
      experience: [
        {
          title: "Senior Frontend Engineer",
          company: "Lumi Health",
          location: "London, UK",
          startDate: "2022-09",
          endDate: null,
          current: true,
          description: "Own the design system and core UI infrastructure for a health platform with 150k monthly active users. Led accessibility audit resulting in WCAG 2.1 AA compliance across the product.",
        },
        {
          title: "Frontend Engineer",
          company: "Ditto Commerce",
          location: "London, UK",
          startDate: "2020-03",
          endDate: "2022-08",
          current: false,
          description: "Built checkout and product catalogue UI using React and TypeScript. Reduced page load time by 35% through code splitting and lazy loading.",
        },
        {
          title: "Graduate Developer",
          company: "BJSS",
          location: "London, UK",
          startDate: "2019-09",
          endDate: "2020-02",
          current: false,
          description: "Consultancy placement on public sector digital services. React, Node.js, and Government Design System.",
        },
      ],
      education: [
        { institution: "University of Warwick", qualification: "MEng", subject: "Computer Systems Engineering", startYear: 2015, endYear: 2019, grade: "First" },
      ],
      skills: ["TypeScript", "React", "Next.js", "Vue.js", "Node.js", "GCP", "PostgreSQL", "Storybook", "Figma", "GraphQL", "Cypress"],
      rightToWork: true,
      noticePeriod: "2 months",
    },
  },
  {
    id: "c-001-03",
    jobId: "job-001",
    name: "Liam Walsh",
    email: "l.walsh@gmail.com",
    phone: "07700 900 345",
    location: "Brighton, UK",
    appliedAt: "2026-04-24T09:30:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 76,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 78, rationale: "4 years JavaScript but TypeScript adoption is recent (1 year)" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 80, rationale: "React experience across two roles, no mention of production scale" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 75, rationale: "Django background; Node.js listed but limited evidence" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 70, rationale: "AWS exposure mentioned in passing; not detailed" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 82, rationale: "Strong SQL background from Django/PostgreSQL work" },
    ],
    status: "reviewing",
    cv: {
      summary: "Software developer with 4 years of experience across Python and JavaScript stacks. Recently transitioning to full-stack TypeScript and enjoying the move. Looking for a team that cares about craft.",
      experience: [
        {
          title: "Software Developer",
          company: "Nexus Agency",
          location: "Brighton, UK",
          startDate: "2022-01",
          endDate: null,
          current: true,
          description: "Full-stack work on client websites and web apps. Django/Python backend, React frontend. Recently migrated key projects to TypeScript.",
        },
        {
          title: "Junior Developer",
          company: "Torchbox",
          location: "Oxford, UK",
          startDate: "2020-06",
          endDate: "2021-12",
          current: false,
          description: "Worked on Wagtail CMS-based projects for charity and public sector clients. Introduced React into the team's frontend workflow.",
        },
      ],
      education: [
        { institution: "University of Sussex", qualification: "BSc", subject: "Software Engineering", startYear: 2017, endYear: 2020, grade: "2:1" },
      ],
      skills: ["Python", "Django", "TypeScript", "React", "PostgreSQL", "AWS", "Docker", "Wagtail", "GraphQL"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-001-04",
    jobId: "job-001",
    name: "Sophie Okafor",
    email: "sophie.okafor@proton.me",
    phone: "07700 900 456",
    location: "London, UK",
    appliedAt: "2026-04-24T11:05:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 84,
    tier: 5,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 88, rationale: "5 years in TypeScript; first company adopted it early" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 86, rationale: "Strong React background; mentions Redux and Zustand" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 82, rationale: "Node/Express APIs built and maintained in production" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 78, rationale: "Azure and some AWS; focus has been application rather than infra" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 86, rationale: "PostgreSQL and MSSQL experience; mentions query tuning" },
      { criterionId: "dc-2", criterionText: "Startup/scale-up", type: "desirable", score: 80, rationale: "Current role is at a Series A startup" },
    ],
    status: "reviewing",
    cv: {
      summary: "Experienced full-stack engineer with a focus on TypeScript, React, and Node.js. Values clear communication and pragmatic engineering. Currently at a Series A SaaS startup where I own two core product areas.",
      experience: [
        {
          title: "Software Engineer",
          company: "Patchwork Health",
          location: "London, UK",
          startDate: "2023-01",
          endDate: null,
          current: true,
          description: "Feature owner for scheduling and shift management modules. TypeScript/React frontend with Node.js backend. Introduced E2E testing with Playwright across the team.",
        },
        {
          title: "Software Engineer",
          company: "Byte Digital",
          location: "London, UK",
          startDate: "2020-09",
          endDate: "2022-12",
          current: false,
          description: "Built and maintained client-facing web apps for brands in retail and finance. Worked closely with designers to implement pixel-perfect UI from Figma.",
        },
      ],
      education: [
        { institution: "City, University of London", qualification: "BSc", subject: "Computer Science", startYear: 2017, endYear: 2020, grade: "2:1" },
      ],
      skills: ["TypeScript", "React", "Node.js", "Express", "PostgreSQL", "Azure", "Redux", "Zustand", "Playwright", "Figma"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-001-05",
    jobId: "job-001",
    name: "Daniel Park",
    email: "dan.park@gmail.com",
    phone: "07700 900 567",
    location: "London, UK",
    appliedAt: "2026-04-25T08:45:00Z",
    source: "reed",
    qualified: false,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "no" }],
    aiScore: 52,
    tier: 2,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 50, rationale: "2.5 years of commercial experience total; does not meet the threshold" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 62, rationale: "React used at current employer but evidence is limited" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 48, rationale: "Backend exposure minimal; primarily frontend role" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 40, rationale: "No cloud infrastructure experience evidenced" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 60, rationale: "MySQL used but at a basic level" },
    ],
    status: "rejected",
    cv: {
      summary: "Junior-to-mid software developer with 2.5 years of experience. Eager to grow and take on more responsibility. Looking for a team where I can learn from experienced engineers.",
      experience: [
        {
          title: "Junior Software Developer",
          company: "Zinc Digital",
          location: "London, UK",
          startDate: "2023-09",
          endDate: null,
          current: true,
          description: "Maintaining and extending a React application for a media client. Also writing basic Node.js scripts for data processing tasks.",
        },
        {
          title: "Web Developer Intern",
          company: "Pixel Studio",
          location: "London, UK",
          startDate: "2023-02",
          endDate: "2023-08",
          current: false,
          description: "HTML/CSS/JS work on marketing websites and landing pages.",
        },
      ],
      education: [
        { institution: "Northumbria University", qualification: "BSc", subject: "Web Development", startYear: 2019, endYear: 2023, grade: "2:2" },
      ],
      skills: ["HTML", "CSS", "JavaScript", "React", "MySQL", "WordPress"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-001-06",
    jobId: "job-001",
    name: "Aisha Patel",
    email: "aisha.patel@btinternet.com",
    phone: "07700 900 678",
    location: "London, UK",
    appliedAt: "2026-04-25T13:22:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 79,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 82, rationale: "4 years JavaScript/TypeScript split across two roles" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 84, rationale: "React used throughout; led a re-architecture of a legacy class-based app" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 75, rationale: "Some Node.js; primarily works on the frontend" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 72, rationale: "AWS S3 and CloudFront; limited deeper infra exposure" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 80, rationale: "PostgreSQL experience; comfortable writing queries and migrations" },
    ],
    status: "new",
    cv: {
      summary: "Frontend-leaning full-stack engineer. Strong React fundamentals and a real interest in performance and developer tooling. Have led small teams and enjoy mentoring.",
      experience: [
        {
          title: "Software Engineer",
          company: "Orbital Labs",
          location: "London, UK",
          startDate: "2022-04",
          endDate: null,
          current: true,
          description: "Building a B2B analytics dashboard in React and TypeScript. Own the data visualisation components and maintain the Node.js data pipeline.",
        },
        {
          title: "Junior Frontend Developer",
          company: "Red Sky Agency",
          location: "Leeds, UK",
          startDate: "2020-07",
          endDate: "2022-03",
          current: false,
          description: "Client work across e-commerce and content sites. React, Gatsby, and headless CMS integrations (Contentful, Sanity).",
        },
      ],
      education: [
        { institution: "University of Leeds", qualification: "BSc", subject: "Computer Science", startYear: 2017, endYear: 2020, grade: "2:1" },
      ],
      skills: ["TypeScript", "React", "Node.js", "PostgreSQL", "AWS", "Gatsby", "Contentful", "Storybook", "Jest", "Figma"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-001-07",
    jobId: "job-001",
    name: "Marcus Reid",
    email: "marcus.reid@hotmail.co.uk",
    phone: "07700 900 789",
    location: "London, UK",
    appliedAt: "2026-04-26T09:00:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 68,
    tier: 3,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 70, rationale: "4 years but split between PHP and JavaScript; TS experience is 1 year" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 72, rationale: "React mentioned across two roles; depth unclear from CV" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 75, rationale: "PHP and some Node; backend experience present but not TypeScript-native" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 60, rationale: "Some Heroku and Vercel usage; no mention of major cloud platforms" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 72, rationale: "MySQL and PostgreSQL across multiple roles" },
    ],
    status: "new",
    cv: {
      summary: "Software developer with experience across PHP and JavaScript ecosystems. Made the switch to TypeScript and React in my last role and loving it. Looking for a team where I can go deeper on modern JS.",
      experience: [
        {
          title: "Full Stack Developer",
          company: "Copper Digital",
          location: "London, UK",
          startDate: "2023-06",
          endDate: null,
          current: true,
          description: "React frontend with a Laravel API backend. Migrated one service to a TypeScript/Node.js stack as part of a modernisation project.",
        },
        {
          title: "PHP Developer",
          company: "WebFoundry",
          location: "Southampton, UK",
          startDate: "2020-01",
          endDate: "2023-05",
          current: false,
          description: "WordPress and custom PHP development for e-commerce clients. Also built React components for a headless front-end project.",
        },
      ],
      education: [
        { institution: "Solent University", qualification: "BSc", subject: "Computing", startYear: 2016, endYear: 2019, grade: "2:2" },
      ],
      skills: ["PHP", "Laravel", "TypeScript", "JavaScript", "React", "MySQL", "PostgreSQL", "WordPress", "Node.js"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-001-08",
    jobId: "job-001",
    name: "Elena Vasquez",
    email: "e.vasquez@live.co.uk",
    phone: "07700 900 890",
    location: "London, UK",
    appliedAt: "2026-04-27T15:10:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 86,
    tier: 5,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 90, rationale: "5 years; TypeScript used exclusively for the last 3" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 88, rationale: "React at scale; mentions Context, Zustand, and React Query" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 85, rationale: "Node.js APIs in production; also mentions Fastify" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 80, rationale: "AWS Lambda and S3 regularly used; Terraform mentioned" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 88, rationale: "PostgreSQL with Prisma ORM; migration history in CV" },
      { criterionId: "dc-1", criterionText: "Next.js and serverless", type: "desirable", score: 88, rationale: "Next.js used extensively; deployed serverless on Vercel and AWS Lambda" },
    ],
    status: "shortlisted",
    cv: {
      summary: "Full-stack TypeScript engineer with 5 years of experience. Strong focus on product quality, testing, and shipping. Currently at a climate tech startup where I'm the first engineering hire.",
      experience: [
        {
          title: "Lead Engineer",
          company: "Verdant Climate",
          location: "London, UK",
          startDate: "2023-10",
          endDate: null,
          current: true,
          description: "First engineering hire at a seed-stage climate tech startup. Built the full product stack from scratch: Next.js frontend, Node.js/Fastify API, PostgreSQL/Prisma, deployed on AWS.",
        },
        {
          title: "Software Engineer",
          company: "Triptease",
          location: "London, UK",
          startDate: "2020-07",
          endDate: "2023-09",
          current: false,
          description: "Worked on a hotel direct booking product used by hundreds of hotel brands globally. TypeScript, React, Node.js. Built A/B testing infrastructure and analytics pipeline.",
        },
      ],
      education: [
        { institution: "UCL", qualification: "BSc", subject: "Computer Science", startYear: 2016, endYear: 2020, grade: "First" },
      ],
      skills: ["TypeScript", "React", "Next.js", "Node.js", "Fastify", "PostgreSQL", "Prisma", "AWS", "Terraform", "Vitest", "Playwright"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-001-09",
    jobId: "job-001",
    name: "Callum Stewart",
    email: "callum.stewart@gmail.com",
    phone: "07700 900 901",
    location: "Edinburgh, UK",
    appliedAt: "2026-04-28T08:20:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 72,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 76, rationale: "4 years; TypeScript more recent but applied in current role" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 74, rationale: "React and Angular experience; more Angular-heavy background" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 78, rationale: "Node.js API development mentioned; some Express experience" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 70, rationale: "Some AWS EC2 and S3; not deep infra experience" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 76, rationale: "PostgreSQL and MySQL across two roles" },
    ],
    status: "new",
    cv: {
      summary: "Software engineer with 4 years experience split between Angular and React frontends. Solid TypeScript skills, good eye for code quality, and experience shipping APIs with Node.js.",
      experience: [
        {
          title: "Software Engineer",
          company: "Skyscanner",
          location: "Edinburgh, UK",
          startDate: "2022-08",
          endDate: null,
          current: true,
          description: "Working on the flights search experience — React/TypeScript frontend with a Node.js BFF layer. Part of an agile squad of 6 engineers.",
        },
        {
          title: "Junior Developer",
          company: "Administrate",
          location: "Edinburgh, UK",
          startDate: "2020-09",
          endDate: "2022-07",
          current: false,
          description: "Angular application for a training management platform. Node.js backend APIs, PostgreSQL database.",
        },
      ],
      education: [
        { institution: "University of Edinburgh", qualification: "BSc", subject: "Informatics", startYear: 2016, endYear: 2020, grade: "2:1" },
      ],
      skills: ["TypeScript", "React", "Angular", "Node.js", "PostgreSQL", "MySQL", "AWS", "Jest", "Docker"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-001-10",
    jobId: "job-001",
    name: "Natasha Brown",
    email: "natasha.b@outlook.co.uk",
    phone: "07700 900 012",
    location: "London, UK",
    appliedAt: "2026-04-29T10:40:00Z",
    source: "totaljobs",
    qualified: false,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "no" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 61,
    tier: 3,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 65, rationale: "5 years but significant portion in non-JS roles" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 60, rationale: "React in recent role; background is primarily Python/Flask" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 72, rationale: "Python/Flask backend experience transfers; some Node exposure" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 68, rationale: "GCP experience from data science background" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 80, rationale: "Strong SQL from data science; PostgreSQL and BigQuery" },
    ],
    status: "rejected",
    cv: {
      summary: "Engineer transitioning from data engineering and Python to full-stack JavaScript. Strong SQL and backend fundamentals, growing React experience. Requires visa sponsorship.",
      experience: [
        {
          title: "Software Engineer",
          company: "Beam Global",
          location: "London, UK",
          startDate: "2024-01",
          endDate: null,
          current: true,
          description: "Full-stack role using Python (FastAPI) and React. Migrated data pipelines to TypeScript-based tooling. Requires Skilled Worker visa sponsorship.",
        },
        {
          title: "Data Engineer",
          company: "Experian",
          location: "Nottingham, UK",
          startDate: "2021-06",
          endDate: "2023-12",
          current: false,
          description: "Built data pipelines using Python and SQL on GCP. Introduced dbt for transformation layer.",
        },
      ],
      education: [
        { institution: "Loughborough University", qualification: "MEng", subject: "Mathematics", startYear: 2017, endYear: 2021, grade: "2:1" },
      ],
      skills: ["Python", "FastAPI", "React", "TypeScript", "PostgreSQL", "BigQuery", "GCP", "dbt", "Airflow"],
      rightToWork: false,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-001-11",
    jobId: "job-001",
    name: "Tom Ashford",
    email: "tomashford@gmail.com",
    phone: "07700 900 123",
    location: "London, UK",
    appliedAt: "2026-04-30T14:00:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 58,
    tier: 2,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 55, rationale: "Claims 4 years but significant time on non-JS stack; TS is very recent" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 60, rationale: "React used in current role but limited in previous positions" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 58, rationale: ".NET background; limited Node.js exposure" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 60, rationale: "Azure from .NET background; less relevant to the role's AWS context" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 78, rationale: "Strong SQL from .NET/MSSQL background" },
    ],
    status: "new",
    cv: {
      summary: "Developer with a .NET background making a deliberate move to TypeScript and React. Learning fast and keen to prove myself in a JavaScript-first team.",
      experience: [
        {
          title: "Developer",
          company: "Atos UK",
          location: "London, UK",
          startDate: "2021-01",
          endDate: null,
          current: true,
          description: "Maintenance and development of a .NET/C# enterprise application. Rebuilt one UI module in React as a pilot project.",
        },
        {
          title: "Junior Developer",
          company: "Fusion Systems",
          location: "London, UK",
          startDate: "2019-06",
          endDate: "2020-12",
          current: false,
          description: "C#/.NET backend, SQL Server database. Standard enterprise CRUD application work.",
        },
      ],
      education: [
        { institution: "University of Hertfordshire", qualification: "BSc", subject: "Computer Science", startYear: 2016, endYear: 2019, grade: "2:2" },
      ],
      skills: ["C#", ".NET", "TypeScript", "React", "SQL Server", "Azure", "Entity Framework"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-001-12",
    jobId: "job-001",
    name: "Rebecca Hobbs",
    email: "rebecca.hobbs@live.co.uk",
    phone: "07700 900 234",
    location: "London, UK",
    appliedAt: "2026-05-01T11:30:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 82,
    tier: 5,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "4+ years TypeScript/JavaScript", type: "essential", score: 86, rationale: "5+ years; TypeScript throughout recent roles" },
      { criterionId: "ec-2", criterionText: "Strong React knowledge", type: "essential", score: 84, rationale: "React at a product company; mentions hooks and performance patterns" },
      { criterionId: "ec-3", criterionText: "Node.js or similar backend", type: "essential", score: 82, rationale: "Node.js across all recent roles; REST and GraphQL APIs built" },
      { criterionId: "ec-4", criterionText: "Cloud infrastructure", type: "essential", score: 78, rationale: "AWS and some GCP; not deeply infrastructure-focused" },
      { criterionId: "ec-5", criterionText: "SQL databases", type: "essential", score: 84, rationale: "PostgreSQL used consistently; mentions migrations and indexing" },
      { criterionId: "dc-2", criterionText: "Startup/scale-up", type: "desirable", score: 78, rationale: "Both roles at growth-stage companies" },
    ],
    status: "reviewing",
    cv: {
      summary: "Full-stack engineer with 5+ years shipping TypeScript products. Comfortable across the stack, opinionated about testing, and a strong written communicator. Currently looking for a product role with ownership.",
      experience: [
        {
          title: "Software Engineer",
          company: "Cleo",
          location: "London, UK",
          startDate: "2023-02",
          endDate: null,
          current: true,
          description: "Fintech app for Gen Z. TypeScript/React Native frontend; Node.js microservices. Built the savings feature from design to production.",
        },
        {
          title: "Software Engineer",
          company: "Bought By Many",
          location: "London, UK",
          startDate: "2020-09",
          endDate: "2023-01",
          current: false,
          description: "Pet insurance SaaS platform. React, Node.js, PostgreSQL. Delivered the claims management workflow end-to-end.",
        },
      ],
      education: [
        { institution: "University of Bath", qualification: "BSc", subject: "Computer Science", startYear: 2016, endYear: 2020, grade: "First" },
      ],
      skills: ["TypeScript", "React", "React Native", "Node.js", "PostgreSQL", "AWS", "GCP", "GraphQL", "Jest", "Playwright"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },

  // ── Job 002 ──────────────────────────────────
  {
    id: "c-002-01",
    jobId: "job-002",
    name: "Hannah Clarke",
    email: "hannah.clarke@gmail.com",
    phone: "07700 900 345",
    location: "Manchester, UK",
    appliedAt: "2026-04-29T09:10:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 89,
    tier: 6,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 95, rationale: "5 years exclusively B2B SaaS; ideal background" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 92, rationale: "Led multiple campaigns; cites pipeline contribution and ROI" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 90, rationale: "HubSpot power user; built attribution model from scratch" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 88, rationale: "Blog posts and case studies mentioned; strong written communication" },
      { criterionId: "dc-1", criterionText: "ABM experience", type: "desirable", score: 85, rationale: "Delivered a Tier 1 ABM pilot targeting 50 accounts" },
    ],
    status: "shortlisted",
    cv: {
      summary: "B2B marketing manager with 5 years in SaaS. Specialise in demand generation and full-funnel campaign strategy. Proven track record of driving pipeline from inbound and content.",
      experience: [
        {
          title: "Marketing Manager",
          company: "Sona HQ",
          location: "Manchester, UK",
          startDate: "2023-04",
          endDate: null,
          current: true,
          description: "Own the full marketing strategy for a workforce management SaaS. 3x'd inbound MQLs in first 12 months. Built ABM programme targeting NHS and care sector.",
        },
        {
          title: "Marketing Executive",
          company: "Cintra HR",
          location: "Manchester, UK",
          startDate: "2021-01",
          endDate: "2023-03",
          current: false,
          description: "Demand gen and content marketing for an HR software business. Managed HubSpot CRM, ran email campaigns, and supported field events.",
        },
      ],
      education: [
        { institution: "University of Manchester", qualification: "BA", subject: "Marketing", startYear: 2017, endYear: 2020, grade: "First" },
      ],
      skills: ["HubSpot", "GA4", "Salesforce", "LinkedIn Ads", "Google Ads", "Copywriting", "SEO", "Content Strategy", "ABM"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-002-02",
    jobId: "job-002",
    name: "Oliver Grant",
    email: "oli.grant@outlook.com",
    phone: "07700 900 456",
    location: "Manchester, UK",
    appliedAt: "2026-04-29T11:45:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 80,
    tier: 5,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 82, rationale: "4 years B2B; mostly agency-side but relevant sector experience" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 80, rationale: "Campaign delivery evidenced; agency context so attribution less clear" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 84, rationale: "HubSpot and Marketo listed; good technical marketing background" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 82, rationale: "Strong portfolio of case studies and website copy" },
      { criterionId: "dc-3", criterionText: "Managing agency relationships", type: "desirable", score: 90, rationale: "Currently manages 3 external agencies from client side" },
    ],
    status: "reviewing",
    cv: {
      summary: "Marketing professional with 4 years of B2B experience, split between agency and in-house roles. Strong campaign delivery and content skills. Now looking to go deep with one product.",
      experience: [
        {
          title: "Senior Marketing Executive",
          company: "DWF Group",
          location: "Manchester, UK",
          startDate: "2023-07",
          endDate: null,
          current: true,
          description: "In-house marketing for a legal and business services firm. Managing agency relationships, email programmes, and content calendar. Owns the HubSpot instance.",
        },
        {
          title: "Account Manager",
          company: "Refresh Agency",
          location: "Manchester, UK",
          startDate: "2021-03",
          endDate: "2023-06",
          current: false,
          description: "B2B SaaS and professional services clients. Managed paid search, SEO, and content campaigns across a portfolio of 8 accounts.",
        },
      ],
      education: [
        { institution: "Manchester Metropolitan University", qualification: "BA", subject: "Business Management", startYear: 2017, endYear: 2020, grade: "2:1" },
      ],
      skills: ["HubSpot", "Marketo", "Google Ads", "LinkedIn Ads", "SEO", "Content Marketing", "CRM", "Copywriting"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-002-03",
    jobId: "job-002",
    name: "Fatima Hussain",
    email: "fatima.h@live.co.uk",
    phone: "07700 900 567",
    location: "Manchester, UK",
    appliedAt: "2026-04-30T10:15:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 85,
    tier: 5,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 88, rationale: "4 years in-house B2B; tech sector focus" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 86, rationale: "Clear pipeline attribution metrics in CV; impressive conversion rates" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 82, rationale: "HubSpot certified; GA4 listed; Salesforce CRM experience too" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 88, rationale: "Strong content portfolio; mentioned writing white papers and long-form" },
      { criterionId: "dc-2", criterionText: "Marketing automation", type: "desirable", score: 85, rationale: "Built automated nurture workflows in HubSpot" },
    ],
    status: "reviewing",
    cv: {
      summary: "Data-driven B2B marketer with 4 years driving demand and pipeline in the tech sector. I treat marketing like a product — hypothesise, test, measure, iterate.",
      experience: [
        {
          title: "Marketing Manager",
          company: "Access Group",
          location: "Manchester, UK",
          startDate: "2023-01",
          endDate: null,
          current: true,
          description: "Demand generation for the hospitality software vertical. Manage a £200k annual media budget. Built an automated nurture programme that improved MQL-to-SQL conversion by 28%.",
        },
        {
          title: "Marketing Executive",
          company: "Mio Technology",
          location: "Leeds, UK",
          startDate: "2020-08",
          endDate: "2022-12",
          current: false,
          description: "Digital marketing for a workplace tech startup. SEO, paid search, and email campaigns. Grew organic traffic by 120% over 18 months.",
        },
      ],
      education: [
        { institution: "University of Leeds", qualification: "BA", subject: "Marketing and Economics", startYear: 2017, endYear: 2020, grade: "2:1" },
      ],
      skills: ["HubSpot", "Salesforce", "GA4", "Google Ads", "LinkedIn Ads", "SEO", "Marketing Automation", "Copywriting", "Data Studio"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-002-04",
    jobId: "job-002",
    name: "George Whitfield",
    email: "george.whitfield@gmail.com",
    phone: "07700 900 678",
    location: "Liverpool, UK",
    appliedAt: "2026-04-30T14:30:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 65,
    tier: 3,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 68, rationale: "3 years but split across B2B and B2C; SaaS experience limited" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 65, rationale: "Campaign experience present but B2C-heavy; pipeline focus unclear" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 70, rationale: "GA4 and Mailchimp listed; HubSpot not mentioned" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 72, rationale: "Consumer copywriting background; tone may need shifting for B2B" },
    ],
    status: "new",
    cv: {
      summary: "Marketing professional with 3 years of experience across digital channels. Strong creative instincts and solid analytical skills. Keen to develop further in B2B SaaS.",
      experience: [
        {
          title: "Digital Marketing Executive",
          company: "The Very Group",
          location: "Liverpool, UK",
          startDate: "2023-09",
          endDate: null,
          current: true,
          description: "Paid social and email marketing for a consumer retail brand. Managed a £500k paid media budget. Responsible for campaign reporting in GA4.",
        },
        {
          title: "Marketing Coordinator",
          company: "Crowdhouse",
          location: "Manchester, UK",
          startDate: "2021-06",
          endDate: "2023-08",
          current: false,
          description: "Content and social media for a property tech platform. Supported launch of B2B partnerships product.",
        },
      ],
      education: [
        { institution: "Liverpool John Moores University", qualification: "BA", subject: "Business and Marketing", startYear: 2018, endYear: 2021, grade: "2:1" },
      ],
      skills: ["GA4", "Mailchimp", "Meta Ads", "Google Ads", "Canva", "Copywriting", "Social Media"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-002-05",
    jobId: "job-002",
    name: "Imogen Sutton",
    email: "imogen.sutton@btinternet.com",
    phone: "07700 900 789",
    location: "Manchester, UK",
    appliedAt: "2026-05-01T09:05:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 74,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 76, rationale: "3.5 years B2B; edtech and professional services sectors" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 74, rationale: "Campaign delivery evidenced; clear pipeline contribution metrics" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 80, rationale: "HubSpot listed and used for reporting; GA4 also mentioned" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 76, rationale: "Email and blog copy; no long-form content mentioned" },
    ],
    status: "new",
    cv: {
      summary: "Marketing manager with 3.5 years of experience in B2B, primarily in professional services and edtech. I enjoy the full lifecycle from planning to reporting and always start with the data.",
      experience: [
        {
          title: "Marketing Manager",
          company: "Aptem",
          location: "Manchester, UK",
          startDate: "2023-06",
          endDate: null,
          current: true,
          description: "In-house marketing for an apprenticeship and skills management platform. Run all demand gen including webinars, email, and SEO. Manage HubSpot and campaign reporting.",
        },
        {
          title: "Marketing Executive",
          company: "BrightHR",
          location: "Manchester, UK",
          startDate: "2021-08",
          endDate: "2023-05",
          current: false,
          description: "Email campaigns and partner marketing for an HR software brand. Managed the content calendar and social channels.",
        },
      ],
      education: [
        { institution: "University of Salford", qualification: "BA", subject: "Media and Communications", startYear: 2018, endYear: 2021, grade: "2:1" },
      ],
      skills: ["HubSpot", "GA4", "Mailchimp", "Canva", "SEO", "Email Marketing", "Webinar Platforms", "Copywriting"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-002-06",
    jobId: "job-002",
    name: "Sean McNally",
    email: "sean.mcnally@hotmail.co.uk",
    phone: "07700 900 890",
    location: "Manchester, UK",
    appliedAt: "2026-05-01T15:50:00Z",
    source: "cvlibrary",
    qualified: false,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "no" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 42,
    tier: 1,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 40, rationale: "2 years experience; below the threshold and consumer-focused" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 44, rationale: "Primarily social media content; no pipeline or demand gen evidence" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 50, rationale: "GA4 mentioned briefly; no CRM or automation experience" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 58, rationale: "Social copy writing; lacks B2B content experience" },
    ],
    status: "rejected",
    cv: {
      summary: "Creative marketing professional with 2 years of experience in social media and content creation. Eager to move into a more strategic B2B role.",
      experience: [
        {
          title: "Social Media Coordinator",
          company: "N Brown Group",
          location: "Manchester, UK",
          startDate: "2024-01",
          endDate: null,
          current: true,
          description: "Managing Instagram, TikTok, and Facebook for a fashion retail brand. Content creation, scheduling, and community management.",
        },
        {
          title: "Marketing Assistant",
          company: "Freelance",
          location: "Manchester, UK",
          startDate: "2023-01",
          endDate: "2023-12",
          current: false,
          description: "Freelance social media and content work for local SMEs.",
        },
      ],
      education: [
        { institution: "Manchester Metropolitan University", qualification: "BA", subject: "Media Studies", startYear: 2019, endYear: 2023, grade: "2:2" },
      ],
      skills: ["Instagram", "TikTok", "Canva", "GA4", "Meta Business Suite", "Copywriting"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-002-07",
    jobId: "job-002",
    name: "Charlotte Barnes",
    email: "c.barnes@gmail.com",
    phone: "07700 900 901",
    location: "Manchester, UK",
    appliedAt: "2026-05-02T10:22:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 91,
    tier: 6,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 95, rationale: "6 years exclusively B2B; SaaS and fintech background" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 92, rationale: "Regularly quotes pipeline numbers and conversion rates; very results-focused CV" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 90, rationale: "HubSpot and Pardot; built data layer for revenue attribution" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 90, rationale: "Award-winning email campaign; speaks on marketing content at events" },
      { criterionId: "dc-1", criterionText: "ABM experience", type: "desirable", score: 92, rationale: "Built and ran ABM strategy targeting enterprise accounts" },
    ],
    status: "shortlisted",
    cv: {
      summary: "Head of Marketing-level operator available at Marketing Manager price point due to family relocation to Manchester. 6 years in B2B SaaS. Results-obsessed, commercially fluent.",
      experience: [
        {
          title: "Head of Marketing",
          company: "Comply365",
          location: "London, UK (remote available)",
          startDate: "2022-06",
          endDate: null,
          current: true,
          description: "Full marketing function ownership at a compliance SaaS business. Built ABM programme from scratch; drove 3x pipeline growth over 18 months. Team of 3. Relocating to Manchester — seeking a new role.",
        },
        {
          title: "Senior Marketing Manager",
          company: "Receipt Bank (now Dext)",
          location: "London, UK",
          startDate: "2020-01",
          endDate: "2022-05",
          current: false,
          description: "Demand generation lead for EMEA. Campaigns across email, paid, events, and partnerships. Awarded Best B2B Campaign at 2021 UK Business Marketing Awards.",
        },
      ],
      education: [
        { institution: "University of Manchester", qualification: "BA", subject: "Business Management", startYear: 2013, endYear: 2016, grade: "2:1" },
      ],
      skills: ["HubSpot", "Pardot", "Salesforce", "Google Ads", "LinkedIn Ads", "ABM", "Content Strategy", "Revenue Attribution", "Copywriting"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-002-08",
    jobId: "job-002",
    name: "Ryan Doyle",
    email: "ryan.doyle@live.co.uk",
    phone: "07700 900 012",
    location: "Manchester, UK",
    appliedAt: "2026-05-03T08:55:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 70,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 72, rationale: "3 years B2B; agency-side which is relevant but less direct" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 70, rationale: "Campaign delivery for B2B clients; results data light" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 76, rationale: "HubSpot and GA4 used across multiple client accounts" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 74, rationale: "Client-facing copy and reports; solid communication skills evidenced" },
      { criterionId: "dc-3", criterionText: "Managing agency relationships", type: "desirable", score: 60, rationale: "Has been the agency — less experience managing them from client side" },
    ],
    status: "new",
    cv: {
      summary: "B2B marketing specialist with 3 years agency-side experience across tech and professional services clients. Now looking to move in-house to take full ownership of a marketing strategy.",
      experience: [
        {
          title: "Senior Account Executive",
          company: "Walker Sands (Manchester)",
          location: "Manchester, UK",
          startDate: "2023-03",
          endDate: null,
          current: true,
          description: "Running integrated B2B campaigns for a portfolio of tech and fintech clients. SEO, PPC, email and content. Account lead on 3 clients.",
        },
        {
          title: "Account Executive",
          company: "Zeal Creative",
          location: "Manchester, UK",
          startDate: "2021-06",
          endDate: "2023-02",
          current: false,
          description: "Multi-channel campaigns for B2B SaaS clients. HubSpot campaigns, paid social, and content planning.",
        },
      ],
      education: [
        { institution: "University of Manchester", qualification: "BA", subject: "Marketing", startYear: 2018, endYear: 2021, grade: "2:1" },
      ],
      skills: ["HubSpot", "GA4", "LinkedIn Ads", "Google Ads", "SEO", "Email Marketing", "Content Marketing", "Copywriting"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-002-09",
    jobId: "job-002",
    name: "Zara Ahmed",
    email: "zara.ahmed@outlook.com",
    phone: "07700 900 123",
    location: "Manchester, UK",
    appliedAt: "2026-05-03T14:10:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 78,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 80, rationale: "4 years B2B across two in-house roles; not SaaS but professional services" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 78, rationale: "Lead gen through events and email; web-led demand gen less evidenced" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 80, rationale: "HubSpot and Salesforce CRM mentioned; strong on reporting" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 84, rationale: "Award entry copy and thought leadership content written; strong writing background" },
    ],
    status: "reviewing",
    cv: {
      summary: "Marketing manager with 4 years of B2B experience in professional services. Strong commercial awareness and a particular love of content-led demand generation.",
      experience: [
        {
          title: "Marketing Manager",
          company: "Shoosmiths LLP",
          location: "Manchester, UK",
          startDate: "2023-09",
          endDate: null,
          current: true,
          description: "Marketing function for a national law firm. Manage BD and demand gen campaigns targeting mid-market businesses. Own the HubSpot CRM and marketing automation.",
        },
        {
          title: "Marketing Executive",
          company: "Grant Thornton",
          location: "Manchester, UK",
          startDate: "2021-01",
          endDate: "2023-08",
          current: false,
          description: "Events, email campaigns, and thought leadership content for the Northern advisory practice. Supported two national campaigns.",
        },
      ],
      education: [
        { institution: "University of Sheffield", qualification: "BA", subject: "English Literature", startYear: 2018, endYear: 2021, grade: "First" },
      ],
      skills: ["HubSpot", "Salesforce", "GA4", "Email Marketing", "Content Strategy", "Events Management", "Copywriting", "LinkedIn Ads"],
      rightToWork: true,
      noticePeriod: "3 months",
    },
  },
  {
    id: "c-002-10",
    jobId: "job-002",
    name: "Adam Fletcher",
    email: "a.fletcher@gmail.com",
    phone: "07700 900 234",
    location: "Manchester, UK",
    appliedAt: "2026-05-04T09:30:00Z",
    source: "totaljobs",
    qualified: false,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "no" }, { questionId: "qq-3", answer: "yes" }],
    aiScore: 48,
    tier: 2,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "3+ years B2B marketing", type: "essential", score: 48, rationale: "1.5 years marketing experience; primarily graduate/junior level" },
      { criterionId: "ec-2", criterionText: "Demand generation campaigns", type: "essential", score: 48, rationale: "No evidence of owning campaigns end-to-end" },
      { criterionId: "ec-3", criterionText: "GA4, HubSpot or similar", type: "essential", score: 54, rationale: "GA4 mentioned as a reporting tool; HubSpot not listed" },
      { criterionId: "ec-4", criterionText: "Copywriting and communication", type: "essential", score: 58, rationale: "Blog writing mentioned; limited professional portfolio" },
    ],
    status: "rejected",
    cv: {
      summary: "Recent graduate with 18 months of marketing experience. Looking to build a career in B2B and develop my demand generation skills.",
      experience: [
        {
          title: "Marketing Coordinator",
          company: "Peel Group",
          location: "Manchester, UK",
          startDate: "2024-09",
          endDate: null,
          current: true,
          description: "Supporting the in-house marketing team with email newsletters, website updates, and event logistics.",
        },
        {
          title: "Marketing Intern",
          company: "Latitude Group",
          location: "Manchester, UK",
          startDate: "2024-02",
          endDate: "2024-08",
          current: false,
          description: "6-month placement supporting social media and content creation.",
        },
      ],
      education: [
        { institution: "University of Salford", qualification: "BA", subject: "Marketing", startYear: 2020, endYear: 2024, grade: "2:1" },
      ],
      skills: ["Social Media", "GA4", "Canva", "Mailchimp", "WordPress", "Copywriting"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },

  // ── Job 003 ──────────────────────────────────
  {
    id: "c-003-01",
    jobId: "job-003",
    name: "Claire Henderson",
    email: "claire.henderson@outlook.com",
    phone: "07700 900 345",
    location: "Bristol, UK",
    appliedAt: "2026-04-03T09:20:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 92,
    tier: 6,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 95, rationale: "CIPD Level 7 qualified" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 94, rationale: "8 years HR experience with extensive ER case management" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 92, rationale: "Regularly presents employment law updates to management; strong evidence" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 90, rationale: "Board-level reporting and coaching senior leaders mentioned" },
      { criterionId: "dc-1", criterionText: "CIPD Level 7", type: "desirable", score: 95, rationale: "Holds CIPD Level 7 — exceeds requirement" },
      { criterionId: "dc-2", criterionText: "Organisational design", type: "desirable", score: 88, rationale: "Led restructure programme affecting 200 roles" },
    ],
    status: "shortlisted",
    cv: {
      summary: "Chartered HR professional (CIPD Level 7) with 8 years of HRBP experience in operations and professional services environments. Trusted senior leader with a pragmatic, commercially grounded approach to people management.",
      experience: [
        {
          title: "HR Business Partner",
          company: "Hargreaves Lansdown",
          location: "Bristol, UK",
          startDate: "2022-03",
          endDate: null,
          current: true,
          description: "Supporting 400 employees across operations and client services. Lead ER cases, support talent and succession, and own the engagement survey action planning for three business units.",
        },
        {
          title: "HR Business Partner",
          company: "Moog Inc.",
          location: "Tewkesbury, UK",
          startDate: "2019-01",
          endDate: "2022-02",
          current: false,
          description: "HRBP to a manufacturing operation of 250 employees. Led a restructure programme affecting 80 roles. Managed TUPE transfers and a complex redundancy process.",
        },
        {
          title: "HR Advisor",
          company: "Computacenter",
          location: "Bristol, UK",
          startDate: "2016-09",
          endDate: "2018-12",
          current: false,
          description: "ER case management across a technology services business. Disciplinaries, grievances, performance management, and long-term sickness cases.",
        },
      ],
      education: [
        { institution: "University of the West of England", qualification: "MA", subject: "Human Resource Management", startYear: 2014, endYear: 2016, grade: "Distinction" },
        { institution: "University of Bath", qualification: "BA", subject: "Business Administration", startYear: 2011, endYear: 2014, grade: "2:1" },
      ],
      skills: ["Employment Law", "ER Case Management", "TUPE", "Organisational Design", "Talent Management", "WorkDay", "SAP HR", "Engagement Surveys"],
      rightToWork: true,
      noticePeriod: "3 months",
    },
  },
  {
    id: "c-003-02",
    jobId: "job-003",
    name: "Jordan Price",
    email: "jordan.price@gmail.com",
    phone: "07700 900 456",
    location: "Bristol, UK",
    appliedAt: "2026-04-04T10:30:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 78,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 80, rationale: "CIPD Level 5 — meets the essential threshold" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 78, rationale: "5 years HR experience; generalist background confirmed" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 76, rationale: "ER case management experience evidenced; law knowledge implied but not explicitly demonstrated" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 76, rationale: "Coaching managers mentioned; evidence of business partnering at mid-senior level" },
    ],
    status: "reviewing",
    cv: {
      summary: "Experienced HR professional with CIPD Level 5 and 5 years of generalist experience. Strong ER background and a straightforward, solutions-focused approach to people management.",
      experience: [
        {
          title: "HR Business Partner",
          company: "Wincanton",
          location: "Bristol, UK",
          startDate: "2023-04",
          endDate: null,
          current: true,
          description: "Supporting logistics and distribution operations teams of 300+ employees. ER case management, absence management, and manager coaching.",
        },
        {
          title: "HR Advisor",
          company: "Mitie Group",
          location: "Bristol, UK",
          startDate: "2020-07",
          endDate: "2023-03",
          current: false,
          description: "Generalist HR support across facilities management contracts. Disciplinary and grievance hearings, TUPE transfers, and line manager support.",
        },
      ],
      education: [
        { institution: "University of Bristol", qualification: "BA", subject: "Sociology", startYear: 2015, endYear: 2018, grade: "2:1" },
        { institution: "CIPD", qualification: "Level 5 Associate Diploma", subject: "People Management", startYear: 2019, endYear: 2020, grade: "Pass" },
      ],
      skills: ["Employee Relations", "TUPE", "Absence Management", "Disciplinary and Grievance", "Coaching", "Workday", "HR Policies"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-003-03",
    jobId: "job-003",
    name: "Sarah Walters",
    email: "sarah.walters@live.co.uk",
    phone: "07700 900 567",
    location: "Bristol, UK",
    appliedAt: "2026-04-05T14:15:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 85,
    tier: 5,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 88, rationale: "CIPD Level 7 in progress; already holds Level 5" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 86, rationale: "6 years HR with a strong ER track record" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 85, rationale: "Employment law frequently cited; previously supported legal team on tribunal cases" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 84, rationale: "Regular senior leadership advisory noted; board reporting in one role" },
      { criterionId: "dc-1", criterionText: "CIPD Level 7", type: "desirable", score: 70, rationale: "Studying towards Level 7; not yet qualified" },
    ],
    status: "shortlisted",
    cv: {
      summary: "Commercially aware HRBP with 6 years of experience, currently studying for CIPD Level 7. Known for clear employment law advice and building strong relationships with operational leaders.",
      experience: [
        {
          title: "HR Business Partner",
          company: "St Mungo's",
          location: "Bristol, UK",
          startDate: "2022-09",
          endDate: null,
          current: true,
          description: "Partnering with the South West operational leadership team for a homelessness charity. Lead ER cases, support recruitment, and deliver management development training. Supported two employment tribunal cases.",
        },
        {
          title: "HR Advisor",
          company: "NHS Property Services",
          location: "Bristol, UK",
          startDate: "2020-01",
          endDate: "2022-08",
          current: false,
          description: "ER specialist in a high-volume NHS support services environment. Complex disciplinary and grievance cases. High-profile long-term sickness and capability management.",
        },
      ],
      education: [
        { institution: "Oxford Brookes University", qualification: "BA", subject: "Human Resource Management", startYear: 2015, endYear: 2019, grade: "2:1" },
        { institution: "CIPD", qualification: "Level 7 Advanced Diploma", subject: "Strategic People Management", startYear: 2023, endYear: 2025, grade: "In Progress" },
      ],
      skills: ["Employee Relations", "Employment Law", "Tribunal Preparation", "Absence Management", "Coaching", "Workday", "Leadership Development"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-003-04",
    jobId: "job-003",
    name: "Michael Rawlinson",
    email: "michael.rawlinson@outlook.com",
    phone: "07700 900 678",
    location: "Bath, UK",
    appliedAt: "2026-04-07T09:45:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 68,
    tier: 3,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 70, rationale: "CIPD Level 5 — meets threshold but no evidence of progression" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 70, rationale: "4 years HR; however, one role was in L&D which is less generalist" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 65, rationale: "Employment law knowledge implied; limited direct ER case evidence" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 68, rationale: "Manager coaching mentioned but senior leadership partnership less evident" },
    ],
    status: "new",
    cv: {
      summary: "HR professional with 4 years of experience spanning L&D and generalist HR. Now focusing on business partnering and seeking a role where I can deepen my ER expertise.",
      experience: [
        {
          title: "HR Business Partner",
          company: "Elior UK",
          location: "Bristol, UK",
          startDate: "2023-09",
          endDate: null,
          current: true,
          description: "HRBP to a catering and facilities services contract. ER case work, manager coaching, and monthly HR reporting. Still developing business partnering confidence at senior leader level.",
        },
        {
          title: "L&D Advisor",
          company: "Lloyds Banking Group",
          location: "Bristol, UK",
          startDate: "2020-06",
          endDate: "2023-08",
          current: false,
          description: "Designed and delivered management skills training programmes. Supported talent reviews and succession planning.",
        },
      ],
      education: [
        { institution: "University of Bath", qualification: "BSc", subject: "Psychology", startYear: 2016, endYear: 2019, grade: "2:1" },
        { institution: "CIPD", qualification: "Level 5 Associate Diploma", subject: "People Management", startYear: 2021, endYear: 2022, grade: "Pass" },
      ],
      skills: ["L&D", "Employee Relations", "Manager Coaching", "Talent Management", "Oracle HR", "Employment Law", "Engagement Surveys"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-003-05",
    jobId: "job-003",
    name: "Beverley Osei",
    email: "beverley.osei@btinternet.com",
    phone: "07700 900 789",
    location: "Bristol, UK",
    appliedAt: "2026-04-09T11:00:00Z",
    source: "cvlibrary",
    qualified: false,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "no" }],
    aiScore: 44,
    tier: 1,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 40, rationale: "CIPD Level 3 only — does not meet the Level 5 requirement" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 50, rationale: "3 years HR; short of 4-year threshold" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 44, rationale: "Basic employment law knowledge; no ER case evidence beyond simple cases" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 42, rationale: "HR admin and coordinator roles; not yet operating at advisor or BP level" },
    ],
    status: "rejected",
    cv: {
      summary: "HR Coordinator with 3 years of experience looking to take the next step into a more senior HR role. CIPD Level 3 qualified, currently considering Level 5.",
      experience: [
        {
          title: "HR Coordinator",
          company: "North Bristol NHS Trust",
          location: "Bristol, UK",
          startDate: "2023-04",
          endDate: null,
          current: true,
          description: "Onboarding, contract administration, and first-line ER support. Referring complex cases to HR Business Partners.",
        },
        {
          title: "HR Administrator",
          company: "University Hospitals Bristol",
          location: "Bristol, UK",
          startDate: "2021-09",
          endDate: "2023-03",
          current: false,
          description: "HR administration including payroll liaison, absence recording, and leaver processing.",
        },
      ],
      education: [
        { institution: "UWE Bristol", qualification: "BA", subject: "Business Studies", startYear: 2018, endYear: 2021, grade: "2:2" },
        { institution: "CIPD", qualification: "Level 3 Foundation Certificate", subject: "People Practice", startYear: 2022, endYear: 2022, grade: "Pass" },
      ],
      skills: ["HR Administration", "Onboarding", "Absence Management", "SAP HR", "Employment Law (basic)"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-003-06",
    jobId: "job-003",
    name: "David Tanner",
    email: "david.tanner@hotmail.co.uk",
    phone: "07700 900 890",
    location: "Swindon, UK",
    appliedAt: "2026-04-12T09:30:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 82,
    tier: 5,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 85, rationale: "CIPD Level 7 Associate — strong qualification" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 84, rationale: "7 years HR experience across two roles; solid generalist background" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 82, rationale: "Employment law training delivered to line managers; strong knowledge demonstrated" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 80, rationale: "Positioned as key advisor to ops directors; board pack contributions mentioned" },
      { criterionId: "dc-3", criterionText: "Professional services background", type: "desirable", score: 72, rationale: "Financial services background relevant; not classic professional services" },
    ],
    status: "reviewing",
    cv: {
      summary: "Senior HRBP with 7 years of experience in financial services and retail. CIPD Level 7 qualified. Known for building trusted relationships with senior leaders and delivering clear, commercially sound HR advice.",
      experience: [
        {
          title: "Senior HR Business Partner",
          company: "Legal & General",
          location: "Swindon, UK",
          startDate: "2021-06",
          endDate: null,
          current: true,
          description: "Supporting 500 employees in the Savings and Retirement division. Lead ER cases, support restructures, and partner with ExCo on workforce planning. Delivered employment law briefings quarterly.",
        },
        {
          title: "HR Business Partner",
          company: "John Lewis Partnership",
          location: "Bristol, UK",
          startDate: "2017-09",
          endDate: "2021-05",
          current: false,
          description: "HRBP for the Bristol branch and wider South West region. Full generalist scope including ER, absence, performance, and engagement.",
        },
      ],
      education: [
        { institution: "Aston University", qualification: "BA", subject: "Human Resource Management", startYear: 2013, endYear: 2016, grade: "First" },
        { institution: "CIPD", qualification: "Level 7 Advanced Diploma", subject: "HRM", startYear: 2017, endYear: 2019, grade: "Distinction" },
      ],
      skills: ["ER Case Management", "Employment Law", "Workforce Planning", "TUPE", "Organisational Design", "Workday", "Leadership Coaching", "Change Management"],
      rightToWork: true,
      noticePeriod: "3 months",
    },
  },
  {
    id: "c-003-07",
    jobId: "job-003",
    name: "Nicola Griffiths",
    email: "nicola.griffiths@gmail.com",
    phone: "07700 900 901",
    location: "Bristol, UK",
    appliedAt: "2026-04-16T15:20:00Z",
    source: "reed",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 74,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 76, rationale: "CIPD Level 5 — meets requirement" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 74, rationale: "4 years generalist; has covered the breadth of HR activity" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 72, rationale: "ER case management evidenced; employment law applied practically if not cited explicitly" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 74, rationale: "Manager relationships described positively; senior leadership advisory at department head level" },
    ],
    status: "reviewing",
    cv: {
      summary: "HR Business Partner with 4 years of generalist experience in logistics and public services. Practical and approachable; well regarded by the managers I partner with.",
      experience: [
        {
          title: "HR Business Partner",
          company: "Bristol City Council",
          location: "Bristol, UK",
          startDate: "2023-03",
          endDate: null,
          current: true,
          description: "Partnering with Adult Social Care directorate (180 employees). Full generalist scope; particularly experienced in long-term sickness management and capability procedures.",
        },
        {
          title: "HR Advisor",
          company: "Imperial Tobacco",
          location: "Bristol, UK",
          startDate: "2020-02",
          endDate: "2023-02",
          current: false,
          description: "HR generalist support in a manufacturing and commercial environment. Disciplinary and grievance cases, redundancy consultation, and TUPE transfers.",
        },
      ],
      education: [
        { institution: "UWE Bristol", qualification: "BA", subject: "Human Resource Management", startYear: 2016, endYear: 2019, grade: "2:1" },
        { institution: "CIPD", qualification: "Level 5 Associate Diploma", subject: "People Management", startYear: 2020, endYear: 2021, grade: "Merit" },
      ],
      skills: ["Employee Relations", "TUPE", "Absence Management", "Employment Law", "Coaching", "iTrent HR System", "Disciplinary and Grievance"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
  {
    id: "c-003-08",
    jobId: "job-003",
    name: "Patrick Daly",
    email: "p.daly@live.co.uk",
    phone: "07700 900 012",
    location: "Bristol, UK",
    appliedAt: "2026-04-19T10:10:00Z",
    source: "cvlibrary",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 58,
    tier: 2,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 60, rationale: "CIPD Level 5 but completed 4 years ago with no progression" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 60, rationale: "4 years HR but heavily weighted towards L&D and training delivery" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 55, rationale: "Limited ER case evidence; employment law knowledge not demonstrated" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 58, rationale: "More trainer than business partner; advisory relationship with managers limited" },
    ],
    status: "rejected",
    cv: {
      summary: "HR and L&D professional with 4 years of experience. Strong facilitation and coaching skills. Looking to shift more firmly into business partnering from an L&D background.",
      experience: [
        {
          title: "People & Culture Advisor",
          company: "Deliveroo",
          location: "Bristol, UK",
          startDate: "2022-10",
          endDate: null,
          current: true,
          description: "Hybrid HR/L&D role. Onboarding, performance review facilitation, and some first-line ER cases. Delivered a management skills programme to 50 team leaders.",
        },
        {
          title: "L&D Coordinator",
          company: "Capita plc",
          location: "Bristol, UK",
          startDate: "2020-04",
          endDate: "2022-09",
          current: false,
          description: "Coordinating and delivering internal training programmes across a customer services operation.",
        },
      ],
      education: [
        { institution: "University of Gloucester", qualification: "BA", subject: "Business Studies", startYear: 2016, endYear: 2019, grade: "2:2" },
        { institution: "CIPD", qualification: "Level 5 Associate Diploma", subject: "People Management", startYear: 2019, endYear: 2021, grade: "Pass" },
      ],
      skills: ["L&D", "Facilitation", "Coaching", "Employee Engagement", "Performance Management", "Employment Law (basic)", "Workday"],
      rightToWork: true,
      noticePeriod: "4 weeks",
    },
  },
  {
    id: "c-003-09",
    jobId: "job-003",
    name: "Amelia Cross",
    email: "amelia.cross@gmail.com",
    phone: "07700 900 123",
    location: "Cheltenham, UK",
    appliedAt: "2026-04-21T14:00:00Z",
    source: "totaljobs",
    qualified: true,
    qualifyingAnswers: [{ questionId: "qq-1", answer: "yes" }, { questionId: "qq-2", answer: "yes" }],
    aiScore: 76,
    tier: 4,
    criterionScores: [
      { criterionId: "ec-1", criterionText: "CIPD Level 5 or above", type: "essential", score: 78, rationale: "CIPD Level 5; mentions working towards Level 7" },
      { criterionId: "ec-2", criterionText: "4+ years HR generalist", type: "essential", score: 76, rationale: "5 years HR; solid generalist CV with ER throughout" },
      { criterionId: "ec-3", criterionText: "UK employment law", type: "essential", score: 78, rationale: "Strong ER track record; references ACAS Code of Practice and employment tribunal awareness" },
      { criterionId: "ec-4", criterionText: "Trusted HR advisor", type: "essential", score: 74, rationale: "Good evidence of manager coaching; CEO-level partnership not yet evidenced" },
    ],
    status: "new",
    cv: {
      summary: "Proactive HRBP with 5 years of HR experience, primarily in retail and hospitality. CIPD Level 5 qualified and working towards Level 7. Strong ER background with a reputation for practical, no-nonsense advice.",
      experience: [
        {
          title: "HR Business Partner",
          company: "Whitbread PLC",
          location: "Cheltenham, UK",
          startDate: "2022-09",
          endDate: null,
          current: true,
          description: "Partnering with hotel and restaurant operations across the Midlands and South West region. ER case management, absence management, and supporting recruitment drives.",
        },
        {
          title: "HR Advisor",
          company: "Primark",
          location: "Bristol, UK",
          startDate: "2020-04",
          endDate: "2022-08",
          current: false,
          description: "High-volume ER in a large retail store environment. Disciplinaries, grievances, appeals, and absence management for 350+ employees.",
        },
      ],
      education: [
        { institution: "Gloucestershire University", qualification: "BA", subject: "Business Management", startYear: 2016, endYear: 2019, grade: "2:1" },
        { institution: "CIPD", qualification: "Level 5 Associate Diploma", subject: "People Management", startYear: 2021, endYear: 2022, grade: "Merit" },
      ],
      skills: ["Employee Relations", "Absence Management", "ACAS Code of Practice", "Disciplinary and Grievance", "Coaching", "Employment Law", "Oracle HR"],
      rightToWork: true,
      noticePeriod: "1 month",
    },
  },
];

// ─────────────────────────────────────────────
// TEAM
// ─────────────────────────────────────────────

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "tm-owner",
    name: "James Hartley",
    email: "james@acmecorp.co.uk",
    canPostJobs: true,
    jobAccess: "all",
    role: "owner",
    joinedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "tm-002",
    name: "Rachel Moore",
    email: "rachel.moore@acmecorp.co.uk",
    canPostJobs: true,
    jobAccess: "all",
    role: "member",
    joinedAt: "2026-03-16T10:00:00Z",
  },
  {
    id: "tm-003",
    name: "Tom Briggs",
    email: "tom.briggs@acmecorp.co.uk",
    canPostJobs: false,
    jobAccess: ["job-001", "job-003"],
    role: "member",
    joinedAt: "2026-04-02T09:30:00Z",
  },
];

// ─────────────────────────────────────────────
// INVOICES
// ─────────────────────────────────────────────

export const INVOICES: Invoice[] = [
  {
    id: "inv-001",
    jobId: "job-001",
    jobTitle: "Senior Software Engineer",
    daysLive: 14,
    dayRate: 19,
    upfrontAmount: 57,
    finalAmount: null,
    total: null,
    status: "partial",
    createdAt: "2026-04-22T09:00:00Z",
    closedAt: null,
  },
  {
    id: "inv-002",
    jobId: "job-002",
    jobTitle: "Marketing Manager",
    daysLive: 8,
    dayRate: 19,
    upfrontAmount: 57,
    finalAmount: null,
    total: null,
    status: "partial",
    createdAt: "2026-04-28T10:30:00Z",
    closedAt: null,
  },
  {
    id: "inv-003",
    jobId: "job-003",
    jobTitle: "HR Business Partner",
    daysLive: 29,
    dayRate: 19,
    upfrontAmount: 57,
    finalAmount: 494,
    total: 551,
    status: "paid",
    createdAt: "2026-04-01T09:00:00Z",
    closedAt: "2026-04-30T23:59:59Z",
  },
];
